#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorY,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorR,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorT,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Temp1 = 30; // Range for Arcade
int Temp2 = 25; // Subtraction for Arcade
int Temp3 = 15; // Range for Tank
float Temp4 = 2; // Tank Drive speed
float Temp5 = 1.5; // Arcade Drive Speed
float Temp6 = 2; // Lift Speed

int vDriver = 1;
int vD1Mode = 1;
int vD1Command = 0;
int vD2Mode = 1;
int vD2Command = 0;

#include<JoystickDriver.c>

void MotorEncoderTarget (int vform, int vleft, int vright, int vpower , int vtime)
{
	nMotorEncoder[motorL] = 0;
	nMotorEncoder[motorR] = 0;

	switch (vform)
	{
		case 1:
			nMotorEncoderTarget[motorL] = vleft;
			nMotorEncoderTarget[motorR] = vright;
			break;
		case 2:
			nMotorEncoderTarget[motorL] = vleft * 115;
			nMotorEncoderTarget[motorR] = vright * 115;
			break;
	}

	if (vleft > 0)
		motor[motorL] = vpower;
	else
		motor[motorL] = -vpower;
	if (vright > 0)
		motor[motorR] = vpower;
	else
		motor[motorR] = -vpower;

	while (nMotorRunState[motorL] != runStateIdle || nMotorRunState[motorR] != runStateIdle)
	{	}

	motor[motorL] = 0;
	motor[motorR] = 0;
	wait10Msec(vtime);

}

void MoveLift (int vdir, int vdist)
{
	switch (vdir)
	{
		case 0:
			break;
		case 1:
			break;
		case 2:
			break;
		case 3:
			break;
		case 4:
			break;
	}

	wait10Msec(10);

}


int Fsignal (int val1)
{
	if (val1 > 0)
	{
		return 1;
	}
	if (val1 == 0)
	{
		return 0;
	}
	if(val1 < 0)
	{
		return -1;
	}
	return 0;
}

int Fsubabs (int val1, int val2)
{

	return (Fsignal(val1) * (abs(val1) - val2));

}


task main()
{ // 01 main +
	waitForStart();

	while(true)
	{ // 02 while +
		if(joy1Btn(1) == 1)
		{
			vD1Mode = 1;
		}
		if(joy1Btn(2) == 1)
		{
			vD1Mode = 2;
		}
		if(joy1Btn(5) == 1)
		{
			Temp4 = 1.2;
		}
		if(joy1Btn(7) == 1)
		{
			Temp4 = 3;
		}
		if(joy1Btn(6) == 1)
		{
			Temp5 = 1.15;
		}
		if(joy1Btn(8) == 1)
		{
			Temp5 = 3;
		}
		if(joy1Btn(10) == 1)
		{
			Temp4 = 2;
			Temp5 = 2;
			wait10Msec(1);
		}

		switch(vD1Mode)
		{
			case 1:
			{ // 05 case +01
				if(joy1Btn(11) == 1 && joy1Btn(12) == 1)
				{ // 06 if +01
					motor[motorL] = 0;
					motor[motorR] = 0;
				} // 06 if -01
				else
				{ // 06 else +01
					if(joystick.joy1_TopHat == -1 && abs(joystick.joy1_y1) < Temp3 && abs(joystick.joy1_y2) < Temp3)
					{ // 07 if +01
						motor[motorL] = 0;
						motor[motorR] = 0;
					} // 07 if -01
					else
					{ // 07 else +01
						if(joystick.joy1_TopHat != -1)
						{ // 08 if +01
							switch(joystick.joy1_TopHat)
							{ // 09 switch +01
								case -1:
									break;
								case 0:
									motor[motorL] = 120/Temp4;
									motor[motorR] = 120/Temp4;
									break;
								case 1:
									motor[motorL] = 120/Temp4;
									motor[motorR] = 0;
									break;
								case 2:
									motor[motorL] = 120/Temp4;
									motor[motorR] = -120/Temp4;
									break;
								case 3:
									motor[motorL] = 0;
									motor[motorR] = -120/Temp4;
									break;
								case 4:
									motor[motorL] = -120/Temp4;
									motor[motorR] = -120/Temp4;
									break;
								case 5:
									motor[motorL] = -120/Temp4;
									motor[motorR] = 0;
									break;
								case 6:
									motor[motorL] = -120/Temp4;
									motor[motorR] = 120/Temp4;
									break;
								case 7:
									motor[motorL] = 0;
									motor[motorR] = 120/Temp4;
									break;
							} // 09 switch -01
						} // 08 if -01
						else
						{ // 08 else +01
							if(joy1Btn(11) == 1)
								motor[motorL] = 0;
							else
							{ // 09 else +01
								if(abs(joystick.joy1_y1) < Temp3)
									motor[motorL] = 0;
								else
									motor[motorL] = joystick.joy1_y1 / Temp4;
							} // 09 else -01
							if(joy1Btn(12) == 1)
								motor[motorR] = 0;
							else
							{ // 09 else +02
								if(abs(joystick.joy1_y2) < Temp3)
									motor[motorR] = 0;
								else
									motor[motorR] = joystick.joy1_y2 / Temp4;
							} // 09 else -02
						} // 08 else -01
					} // 07 else -01
				} // 06 else -01
			} // 05 case -01
				break;
			case 2:
			{ // 05 case +02
				if(joy1Btn(11) == 1)
				{ // 06 if +02
					motor[motorL] = 0;
					motor[motorR] = 0;
				} // 06 if -02
				else
				{	// 06 else +02
					if((abs(joystick.joy1_y1) < Temp1) || (abs(joystick.joy1_x1) < Temp1))
					{ // 07 if +01
						if((abs(joystick.joy1_y1) < Temp1) && (abs(joystick.joy1_x1) < Temp1))
						{ // 08 if +01
							motor[motorL] = 0;
							motor[motorR] = 0;
						} // 08 if -01
						else
						{ // 08 else +01
							if (abs(joystick.joy1_x1) < Temp1)
							{ // 09 if +01
								motor[motorL] = Fsubabs(joystick.joy1_y1, Temp2) / Temp5;
								motor[motorR] = Fsubabs(joystick.joy1_y1, Temp2) / Temp5;
							} // 09 if -01
							if (abs(joystick.joy1_y1) < Temp1)
							{ // 09 if +02
								motor[motorL] = Fsubabs(joystick.joy1_x1, Temp2) / Temp5;
								motor[motorR] = -(Fsubabs(joystick.joy1_x1, Temp2)) / Temp5;
							} // 09 if -02
						} // 08 else -01
					} // 07 if -01
					else
					{ // 07 else +01
						switch (Fsignal(joystick.joy1_y1) * Fsignal(joystick.joy1_x1))
						{ // 08 switch +01
							case -1:
								if (abs(joystick.joy1_y1) >= abs(joystick.joy1_x1))
								{ // 09 if +01
									motor[motorL] = (Fsubabs(joystick.joy1_y1, Temp2) + Fsubabs(joystick.joy1_x1, Temp2)) / Temp5;
									motor[motorR] = Fsubabs(joystick.joy1_y1, Temp2) / Temp5;
								} // 09 if -01
								else
								{ // 09 else +01
									motor[motorR] = Fsignal(joystick.joy1_y1) * abs(Fsubabs(joystick.joy1_x1, Temp2)) / Temp5;
									motor[motorL] = (Fsubabs(joystick.joy1_x1, Temp2) + Fsubabs(joystick.joy1_y1, Temp2)) / Temp5;
								} // 09 else -01
								break;
							case 1:
								if (abs(joystick.joy1_y1) >= abs(joystick.joy1_x1))
								{ // 09 if +02
									motor[motorL] = Fsubabs(joystick.joy1_y1, Temp2) / Temp5;
									motor[motorR] = (Fsubabs(joystick.joy1_y1, Temp2) - Fsubabs(joystick.joy1_x1, Temp2)) / Temp5;
								} // 09 if -02
								else
								{ // 09 else +02
									motor[motorR] = - (Fsubabs(joystick.joy1_x1, Temp2) - Fsubabs(joystick.joy1_y1, Temp2)) / Temp5;
									motor[motorL] = Fsignal(joystick.joy1_y1) * abs(Fsubabs(joystick.joy1_x1, Temp2)) / Temp5;
								} // 09 else -02
								break;
						} // 08 switch +01
					} // 07 else -01
				} // 06 else +02
			} // 05 case -02
				break;
		} // 04 switch -01

		if(joy2Btn(12) == 1)
		{
			motor[motorY] = 0;
		}
		else
		{
			if(abs(joystick.joy2_y2) < Temp3)
			{
				motor[motorY] = 0;
			}
			else
			{
				motor[motorY] = (joystick.joy2_y2 - Temp3) / Temp6;
			}
		}
		if(joy2Btn(11) == 1)
		{
			motor[motorT] = 0;
		}
		else
		{
			if(abs(joystick.joy2_y1) < Temp3)
			{
				motor[motorT] = 0;
			}
			else
			{
				motor[motorT] = (joystick.joy2_y1 - Temp3) / Temp6;
			}
		}

		if(joy2Btn(6) == 1)
		{
			Temp6 = 1.5;
		}
		if(joy2Btn(8) == 1)
		{
			Temp6 = 3;
		}
		if(joy2Btn(10) == 1)
		{
			Temp6 = 0.5;
			wait10Msec(1);
		}
		if(joy2Btn(4) == 1)
		{
			motor[motorT] = 50;
			wait10Msec(50);
			motor[motorT] = -50;
			wait10Msec(50);
			motor[motorT] = 0;
		}

		nxtDisplayCenteredTextLine(2, "%d, %.1f, %.1f, %.1f", vD1Mode, Temp4, Temp5, Temp6);

	} // 02 while -
} // 01 main -
